### ISSUE TITLE
xacro undefined substitution argument

### ISSUE THREAD

**Issue by ravi-chepuri** [se1exin/ros2_ar4#1]
Hi, I am following the setup instructions to run moveit_test. ar_gazebo launches just fine, but when I try to launch av_moveit_test xacro throws an "undefined substitution argument" error. Any ideas how to fix this?

Thanks!

```
> ros2 launch ar_testing ar_moveit_test.launch.py use_sim_time:=True 
[INFO] [launch]: All log files can be found below /home/rchepuri99/.ros/log/2024-07-17-19-49-24-882715-UbuntuJammy-18868
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch]: Caught exception in launch (see debug for traceback): executed command failed. Command: /opt/ros/iron/bin/xacro /home/rchepuri99/ros2_ar4/install/ar_description/share/ar_description/urdf/ar.urdf.xacro name:=ar include_gripper:=True
Captured stderr output: error: Undefined substitution argument ar_model
when processing file: /home/rchepuri99/ros2_ar4/install/ar_description/share/ar_description/urdf/ar.urdf.xacro
```

**Comment by ravi-chepuri** [comment]
Fixed it: in the urdf file from the driver `lib/ar4_ros_driver/ar_description/urdf/ar.urdf.xacro`, just had to replace all instances of `$(arg ar_model)` with `ar4_mk3` (or `ar4`)

**Comment by se1exin** [comment]
@ravi-chepuri which repo are you using for the `ar4_ros_driver`?  I've been using my own fork (mentioned in the README) that doesn't include the `ar_model` param from ycheng517's repo.

**Comment by ravi-chepuri** [comment]
Got it. I cloned directly from ycheng517's repo - I'd imagine using your fork would fix it right away. Thanks!
